// stairpts.js <port> : HHS under-stair witness (parent's §STAIR_GRID …1790662836953, 49 floor points whose up-ray hits the stair flight
// 2x4PKsKvfDM97UO7ZhjXbT or stair slabs). Local db, SW bypassed; LightZones.build + field; per point F = skyField(p, up) vs exact E
// (256 CIE-overcast x cos rays at p + 3 cm and at p + 0.25 m, every visible mesh, glass T per pane). Prints §STAIR_UNDER.
const puppeteer = require('/home/red1/bim-compiler/node_modules/puppeteer'), fs = require('fs'); const sleep = ms => new Promise(r => setTimeout(r, ms));
const PORT = process.argv[2], PTS = JSON.parse(fs.readFileSync(__dirname + '/stairpts.json', 'utf8'));
(async () => { const b = await puppeteer.launch({ headless: true, userDataDir: __dirname + '/prof_' + PORT, protocolTimeout: 7200000, env: Object.assign({}, process.env, { __EGL_VENDOR_LIBRARY_FILENAMES: '/usr/share/glvnd/egl_vendor.d/10_nvidia.json' }), args: ['--no-sandbox', '--use-angle=gl-egl', '--ignore-gpu-blocklist'] });
  const p = await b.newPage(); await p.setBypassServiceWorker(true); await p.setViewport({ width: 800, height: 450 }); const L = []; p.on('console', m => { const t = m.text(); if (/^§(SKY_FIELD_EXACT_ALL|ZONE_IDB_CACHE hit)|Uncaptured WebGPU/.test(t)) L.push(t.slice(0, 600)); });
  await p.goto('http://127.0.0.1:' + PORT + '/viewer/viewer.html?db=../buildings/HHS_Office_Federated_extracted.db' + (process.env.Q || ''), { waitUntil: 'domcontentloaded' });
  { let last = -1, same = 0; for (let i = 0; i < 400 && same < 5; i++) { await sleep(2000); const n = await p.evaluate(() => window.APP && window.APP.guidMap ? Object.keys(window.APP.guidMap).length : 0); if (n > 0 && n === last) same++; else same = 0; last = n; } }
  const R = await p.evaluate(async (pts) => { const A = window.APP, T = window.THREE, LZ = window.LightZones; if (LZ.prime) { try { await LZ.prime(A); } catch (e) {} } LZ.build(A); const F = LZ.field(A);
    const tg = []; A.scene.traverse(o => { if ((o.isMesh || o.isInstancedMesh || o.isBatchedMesh) && o !== A._sky) { let q = o, v = true; while (q) { if (!q.visible) v = false; q = q.parent; } const m = Array.isArray(o.material) ? o.material[0] : o.material; if (v && m && !m.isMeshBasicMaterial) tg.push(o); } });
    const matOf = q => Array.isArray(q.object.material) ? q.object.material[(q.face && q.face.materialIndex) || 0] : q.object.material, glassy = m => !!(m && m.transparent && m.opacity < 0.95 && !m.map);
    const rc = new T.Raycaster(), tr = (P0, d) => { rc.set(P0, d); rc.far = 500; let Tt = 1, last = -1; for (const h of rc.intersectObjects(tg, false)) { const m = matOf(h); if (glassy(m)) { if (last < 0 || h.distance - last > 0.3) Tt *= 1 - m.opacity; last = h.distance + 0.01; continue; } return 0; } return Tt; };
    const muOf = u => { let m = Math.sqrt(u); for (let i = 0; i < 12; i++) { const f = (m * m / 2 + 2 * m * m * m / 3) * 6 / 7 - u, df = (m + 2 * m * m) * 6 / 7; m -= f / (df || 1e-6); m = Math.min(1, Math.max(0, m)); } return m; };
    let seed = 7; const rnd = () => { seed = (seed * 16807) % 2147483647; return seed / 2147483647; }, E = (x, y, z) => { let s = 0; const P0 = new T.Vector3(x, y, z); for (let a = 0; a < 16; a++) for (let c = 0; c < 16; c++) { const mu = muOf((a + rnd()) / 16), ph = 2 * Math.PI * (c + rnd()) / 16, r = Math.sqrt(1 - mu * mu); s += tr(P0, new T.Vector3(r * Math.cos(ph), mu, r * Math.sin(ph))); } return s / 256; };
    const up = { x: 0, y: 1, z: 0 }; return { cached: !!F.cached, rows: pts.map(q => { const sf = LZ.skyField({ x: q.p[0], y: q.p[1], z: q.p[2] }, up); return { p: q.p, F0: q.F0, zone0: q.zone0, Lf: q.Lf, F: sf.F == null ? null : +sf.F.toFixed(4), zone: sf.zone, E: +E(q.p[0], q.p[1] + 0.03, q.p[2]).toFixed(4), E25: +E(q.p[0], q.p[1] + 0.25, q.p[2]).toFixed(4) }; }) }; }, PTS);
  const z0 = R.rows.filter(r => r.zone0 === 0), oth = R.rows.filter(r => r.zone0 !== 0), md = v => { v = v.slice().sort((a, c) => a - c); return v.length ? v[v.length >> 1] : null; };
  const line = '§STAIR_UNDER HHS …1790662836953 points=' + R.rows.length + ' fieldCached=' + R.cached + ' | stairOpen(zone0 in v1502)=' + z0.length + ' F v1502 median ' + md(z0.map(r => r.F0)) + ' -> now median ' + md(z0.map(r => r.F)) + ' (min ' + Math.min(...z0.map(r => r.F)) + ' max ' + Math.max(...z0.map(r => r.F)) + ') truth E median ' + md(z0.map(r => r.E)) + ' E25 median ' + md(z0.map(r => r.E25)) + ' stillF1=' + z0.filter(r => r.F >= 0.999).length +
    ' | covered=' + oth.length + ' F v1502 median ' + md(oth.map(r => r.F0)) + ' -> now ' + md(oth.map(r => r.F)) + ' truth E median ' + md(oth.map(r => r.E)) + ' E25 ' + md(oth.map(r => r.E25));
  L.push(line); R.rows.forEach(r => L.push(JSON.stringify(r))); fs.writeFileSync(__dirname + '/stair_' + (process.env.SUF || 'x') + '.log', L.join('\n') + '\n'); console.log(line); await b.close(); })().catch(e => { console.log('FATAL ' + e.message); process.exit(1); });
