// walle.js <port> <png> : lattice F vs exact sky E on ANY surface (walls included) at PX pixels of the PNG pose. No Alt+S: page load,
// LightZones.build + field (sidecar / IndexedDB), then per pixel: first opaque hit, eye-facing n, F = skyField, E = 64 CIE-overcast x cos
// rays about n (above-horizon only; glass x (1 - opacity)). Prints §WALL_E rows.
const puppeteer = require('/home/red1/bim-compiler/node_modules/puppeteer'), fs = require('fs'); const sleep = ms => new Promise(r => setTimeout(r, ms));
const [PORT, PNG] = process.argv.slice(2);
function pose(f) { const d = fs.readFileSync(f); let i = 8; while (i < d.length) { const n = d.readUInt32BE(i), t = d.toString('latin1', i + 4, i + 8), c = d.slice(i + 8, i + 8 + n); i += 12 + n;
  if (t === 'tEXt') { const z = c.indexOf(0); if (c.toString('latin1', 0, z) === 'bim-still-pose') return JSON.parse(c.slice(z + 1).toString('utf8')); } } }
(async () => { const b = await puppeteer.launch({ headless: true, userDataDir: process.env.PROF || undefined, protocolTimeout: 3600000, env: Object.assign({}, process.env, { __EGL_VENDOR_LIBRARY_FILENAMES: '/usr/share/glvnd/egl_vendor.d/10_nvidia.json' }), args: ['--no-sandbox', '--use-angle=gl-egl', '--ignore-gpu-blocklist'] });
  const P = pose(PNG), p = await b.newPage(); await p.setBypassServiceWorker(true); const L = []; p.on('console', m => { const t = m.text(); if (/^§(SKY_FIELD_EXACT_ALL|ZONE_IDB_CACHE hit|LIGHT_FIELD_PATCH)|Uncaptured WebGPU/.test(t)) L.push(t.slice(0, 400)); }); await p.setViewport({ width: P.w, height: P.h });
  await p.goto('http://127.0.0.1:' + PORT + '/viewer/viewer.html' + P.url + (process.env.Q || ''), { waitUntil: 'domcontentloaded' });
  { let last = -1, same = 0; for (let i = 0; i < 400 && same < 5; i++) { await sleep(2000); const n = await p.evaluate(() => window.APP && window.APP.guidMap ? Object.keys(window.APP.guidMap).length : 0); if (n > 0 && n === last) same++; else same = 0; last = n; } }
  const R = await p.evaluate(async (c, t, px, W, H) => { const A = window.APP, T = window.THREE, LZ = window.LightZones; A.camera.position.fromArray(c); A.controls.target.fromArray(t); A.controls.update(); A.camera.updateMatrixWorld();
    if (LZ.prime) { try { await LZ.prime(A); } catch (e) {} } LZ.build(A); const F = LZ.field(A);
    const tg = []; A.scene.traverse(o => { if ((o.isMesh || o.isInstancedMesh || o.isBatchedMesh) && o.visible && o !== A._sky) { const m = Array.isArray(o.material) ? o.material[0] : o.material; if (m && !m.isMeshBasicMaterial) tg.push(o); } });
    const matOf = q => Array.isArray(q.object.material) ? q.object.material[(q.face && q.face.materialIndex) || 0] : q.object.material, glassy = m => !!(m && m.transparent && m.opacity < 0.95 && !m.map);
    const rc = new T.Raycaster(), muOf = u => { let m = Math.sqrt(u); for (let i = 0; i < 12; i++) { const f = (m * m / 2 + 2 * m * m * m / 3) * 6 / 7 - u, df = (m + 2 * m * m) * 6 / 7; m -= f / (df || 1e-6); m = Math.min(1, Math.max(0, m)); } return m; };
    let seed = 5; const rnd = () => { seed = (seed * 16807) % 2147483647; return seed / 2147483647; }; const out = { cached: !!F.cached, rows: [] };
    for (const [x, y] of px) { rc.setFromCamera(new T.Vector2(x / W * 2 - 1, 1 - y / H * 2), A.camera); rc.far = 1000; const q = rc.intersectObjects(tg, false).find(h => !glassy(matOf(h))); if (!q || !q.face) continue;
      const n = q.face.normal.clone().transformDirection(q.object.matrixWorld); if (n.dot(A.camera.position.clone().sub(q.point)) < 0) n.negate(); const P0 = q.point.clone().addScaledVector(n, 0.03), sf = LZ.skyField(q.point, n);
      const t1 = new T.Vector3(Math.abs(n.y) < 0.9 ? 0 : 1, Math.abs(n.y) < 0.9 ? 1 : 0, 0).cross(n).normalize(), t2 = new T.Vector3().crossVectors(n, t1), d = new T.Vector3(); let E = 0, hitCls = {};
      for (let a = 0; a < 16; a++) for (let b2 = 0; b2 < 16; b2++) { const mu = muOf((a + rnd()) / 16), ph = 2 * Math.PI * (b2 + rnd()) / 16, r = Math.sqrt(1 - mu * mu); d.copy(n).multiplyScalar(mu).addScaledVector(t1, r * Math.cos(ph)).addScaledVector(t2, r * Math.sin(ph)); if (d.y <= 0) continue;
        rc.set(P0, d); rc.far = 500; let Tt = 1; for (const h of rc.intersectObjects(tg, false)) { const m = matOf(h); if (glassy(m)) { Tt *= 1 - m.opacity; continue; } Tt = 0; break; } E += Tt; }
      out.rows.push({ px: [x, y], p: q.point.toArray().map(v => +v.toFixed(2)), n: n.toArray().map(v => +v.toFixed(2)), zone: sf.zone, F: sf.F == null ? null : +sf.F.toFixed(4), E: +(E / 256).toFixed(4), Eh: +(() => { const Q = q.point.clone().addScaledVector(n, 0.25); let s = 0; for (let a = 0; a < 16; a++) for (let b2 = 0; b2 < 16; b2++) { const mu = muOf((a + rnd()) / 16), ph = 2 * Math.PI * (b2 + rnd()) / 16, r = Math.sqrt(1 - mu * mu); rc.set(Q, new T.Vector3(r * Math.cos(ph), mu, r * Math.sin(ph))); rc.far = 500; let Tt = 1; for (const h of rc.intersectObjects(tg, false)) { const m = matOf(h); if (glassy(m)) { Tt *= 1 - m.opacity; continue; } Tt = 0; break; } s += Tt; } return s / 256; })().toFixed(4) }); }
    return out; }, P.cam, P.tgt, JSON.parse(fs.readFileSync(process.env.PX, 'utf8')), P.w, P.h);
  L.forEach(t => console.log('  ' + t)); console.log('§WALL_E cached=' + R.cached); R.rows.forEach(r => console.log(JSON.stringify(r)));
  const G = {}; R.rows.forEach(r => { if (r.F == null) return; const k = r.n.map(v => Math.round(v)).join(','), g = G[k] || (G[k] = []); g.push(r); });
  Object.entries(G).forEach(([k, g]) => { const rng = f => [Math.min(...g.map(f)).toFixed(4), Math.max(...g.map(f)).toFixed(4)].join('..'); console.log('§WALL_E_SUM n=[' + k + '] px=' + g.length + ' F ' + rng(r => r.F) + ' E(normal) ' + rng(r => r.E) + ' Eh(field integrand p+0.25n) ' + rng(r => r.Eh) + ' max|F-E| ' + Math.max(...g.map(r => Math.abs(r.F - r.E))).toFixed(4) + ' max|F-Eh| ' + Math.max(...g.map(r => Math.abs(r.F - r.Eh))).toFixed(4) + ' within0.01(E) ' + g.filter(r => Math.abs(r.F - r.E) <= 0.01).length + '/' + g.length); }); await b.close(); })().catch(e => { console.log('FATAL ' + e.message); process.exit(1); });
