#!/usr/bin/env python3
"""Generates validity_tables.js from ifcopenshell's bundled EXPRESS schema objects (extract, not invented).
Per entity (UPPERCASE name) -> flags string: first char 'R' rooted(IfcRoot subtype) | '-' ; second 'P' IfcRepresentation subtype | '-';
third 'A' abstract | '-'; then one char per STEP argument slot (supertypes first): 'm' mandatory explicit, 'o' optional explicit, 'd' derived (written '*').
Deterministic: sorted names. Usage: python3 gen_validity_tables.py > validity_tables.js"""
import json, sys, ifcopenshell, ifcopenshell.ifcopenshell_wrapper as w
SCHEMAS = ['IFC2X3', 'IFC4', 'IFC4X3_ADD2']
def sup_chain(e):
    while e is not None:
        yield e.name()
        e = e.supertype()
out = {}
for sn in SCHEMAS:
    s = w.schema_by_name(sn); t = {}
    for d in s.entities():
        e = d.as_entity() if hasattr(d, 'as_entity') else d
        chain = set(sup_chain(e))
        attrs = e.all_attributes(); der = e.derived()
        assert len(attrs) == len(der), (sn, e.name())
        fl = ''.join('d' if der[i] else ('o' if a.optional() else 'm') for i, a in enumerate(attrs))
        t[e.name().upper()] = ('R' if 'IfcRoot' in chain else '-') + ('P' if 'IfcRepresentation' in chain else '-') + ('A' if e.is_abstract() else '-') + fl
    out[sn] = dict(sorted(t.items()))
print('/* GENERATED by gen_validity_tables.py from ifcopenshell %s EXPRESS schema objects; do not hand-edit. */' % ifcopenshell.version)
print('var VALIDITY_TABLES = ' + json.dumps(out, separators=(',', ':')) + ';')
print("if (typeof module !== 'undefined') module.exports = VALIDITY_TABLES;")
