# cp_sync_tags.py — regenerate the <!-- §CP-SCRIPTS --> block in erp/idempiere.html + the sw.js precache entries
# from the files present in erp/callouts/ and erp/processes/ (support files first). usage: python3 cp_sync_tags.py <ootb>
import os, re, sys
root = sys.argv[1] if len(sys.argv) > 1 else '/tmp/wt-callouts'
erp = os.path.join(root, 'erp')
def files(d, first):
    fs = sorted(f for f in os.listdir(os.path.join(erp, d)) if f.endswith('.js')) if os.path.isdir(os.path.join(erp, d)) else []
    head = [f for f in first if f in fs]
    return [d + '/' + f for f in head + [f for f in fs if f not in head]]
cl = files('callouts', ['support.js', 'support_stock.js', 'views.js', 'currency.js', 'uom.js', 'pricing.js', 'tax.js', 'sqlfn.js'])
pr = files('processes', [])
block = ['<!-- §CP-SCRIPTS (bim-compiler prompts/ERP_IDEMPIERE_UX_PARITY.md §CP) — the callout runtime + verbatim callout/process ports.',
         '     Generated by bim-compiler scripts/pilot/cp_sync_tags.py; after bigdecimal.js + model_layer.js. -->',
         '<script src="ad_callout.js?v=3"></script>'] + ['<script src="%s?v=1"></script>' % f for f in cl + pr] + ['<!-- /§CP-SCRIPTS -->']
p = os.path.join(erp, 'idempiere.html'); s = open(p).read()
s = re.sub(r'<script src="ad_callout\.js\?v=\d+"></script>\n', '', s, count=1) if '§CP-SCRIPTS' not in s else s
if '<!-- §CP-SCRIPTS' in s:
    s = re.sub(r'<!-- §CP-SCRIPTS.*?<!-- /§CP-SCRIPTS -->', '\n'.join(block), s, flags=re.S)
else:
    anchor = re.search(r'<script src="model_post\.js\?v=\d+"></script>\n', s)
    s = s[:anchor.end()] + '\n'.join(block) + '\n' + s[anchor.end():]
open(p, 'w').write(s)
sw = os.path.join(erp, 'sw.js'); w = open(sw).read()
want = [f for f in cl + pr if "'" + f + "'" not in w]
if want:
    w = w.replace("  'ad_callout.js',", "  'ad_callout.js',\n" + ''.join("  '%s',\n" % f for f in want).rstrip('\n'), 1)
    open(sw, 'w').write(w)
print('§CP-TAGS callouts=%d processes=%d sw_added=%d' % (len(cl), len(pr), len(want)))
