#!/bin/sh
# Run every Bridge witness + the genericity gate against the LOCAL PILOT; persist the full log (CLAUDE.md log mandate) and print only verdict/finding lines.
# Needs: docker postgres (idempiere_pilot) + pilot server :8088 (~/idempiere-pilot/start.sh).
cd "$(dirname "$0")" || exit 1
d="$HOME/.cache/bim_bridge"; mkdir -p "$d"; log="$d/run_$(date +%Y%m%d_%H%M%S).log"
{
  ./check_genericity.sh
  for w in witness_changelog_tail witness_m1_outbox witness_m2_replay witness_dict_diff witness_m3_gap; do echo "=== $w"; node "$w.js"; done
} > "$log" 2>&1
grep -E "^§GENERICITY|_VERDICT|^§DD_TABLE|^§DD_COLUMNS|^§DICT_GAP|^§RECON_SUMMARY|^§SCN |^§GAP |^§M3_FINDINGS" "$log"
# TRIAGE (spec §26): DATA gaps are generated by dict_diff (patches in out/); whatever SQLITE-GAP remains with a clean dictionary is a RULE (engine lane).
data=$(grep -c "^§DICT_GAP" "$log"); cols=$(grep -c "^§DD_COLUMNS" "$log"); rule=$(grep "^§SCN .*SQLITE-GAP" "$log" | grep -v " NEG-" | awk '{print $2}' | tr '\n' ' ')
echo "§TRIAGE DATA_gaps=$data SCHEMA_gaps(tables lacking legacy columns)=$cols RULE_queue=[${rule}] (fix DATA/SCHEMA first via patch+loader; a RULE listed while SCHEMA_gaps>0 may depend on it — see spec §29)"
echo "full log: $log"
grep -q -E "_VERDICT (FAIL|HARNESS-FAIL)|GENERICITY FAIL" "$log" && exit 1
exit 0
