#!/usr/bin/env python3
"""§STOREY_AGGREGATE_INHERIT patch generator — emit the storey a shipped DB is missing.

⚠ DO NOT REMOVE — scope: an already-distributed *_extracted.db predates tools/extract.py's
§STOREY_AGGREGATE_INHERIT fix, so every part of a decomposed element still carries storey
'Unknown'. Re-extraction is the permanent fix; this emits the same answer as a patch so a LIVE
user gets it without a binary DB moving (CLAUDE.md: DB CHANGES = MIGRATION SCRIPT + SELF-HEAL
LOADER). Read the log after every run — the exit code is not evidence.

The storey is taken from the SOURCE IFC through the fixed rule, never guessed: this writes only
what extract.py itself would now write. Rows already carrying a real storey are left alone by the
WHERE clause, so the patch is idempotent and safe to re-apply.

  python3 scripts/gen_storey_patch.py OUT.sql SOURCE.ifc [SOURCE2.ifc ...]
"""
import sys, os, collections
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'tools'))
import ifcopenshell
import extract as E


def old_rule(element):
    """extract.py's containment-only rule, as it stood before §STOREY_AGGREGATE_INHERIT."""
    SC = ("IfcBuildingStorey", "IfcFacilityPart")
    try:
        for rel in element.ContainedInStructure:
            c = rel.RelatingStructure
            if any(c.is_a(t) for t in SC):
                return E.normalize_storey(c.Name)
            if hasattr(c, "Decomposes"):
                for d in c.Decomposes:
                    if any(d.RelatingObject.is_a(t) for t in SC):
                        return E.normalize_storey(d.RelatingObject.Name)
    except (AttributeError, TypeError):
        pass
    return "Unknown"


def main(out_path, ifc_paths):
    rows, per_storey, per_class, seen = [], collections.Counter(), collections.Counter(), set()
    for p in ifc_paths:
        f = ifcopenshell.open(p)
        for elem in f.by_type("IfcProduct"):
            guid = getattr(elem, "GlobalId", None)
            if not guid or guid in seen:
                continue
            if old_rule(elem) != "Unknown":
                continue                      # the shipped DB already has a real storey
            new = E.get_storey_for_element(elem)
            if new == "Unknown":
                continue                      # the fix does not know either — leave it alone
            seen.add(guid)
            rows.append((guid, new, elem.is_a()))
            per_storey[new] += 1
            per_class[elem.is_a()] += 1
    with open(out_path, "w") as fh:
        fh.write("-- §STOREY_AGGREGATE_INHERIT — storey for parts of decomposed elements\n")
        fh.write("-- Generated by scripts/gen_storey_patch.py from: " + ", ".join(os.path.basename(p) for p in ifc_paths) + "\n")
        fh.write("-- Every value comes from the SOURCE IFC through tools/extract.py's fixed rule.\n")
        fh.write("-- Idempotent: the WHERE clause never overwrites a storey that is already real.\n")
        for guid, storey, cls in rows:
            fh.write("UPDATE elements_meta SET storey='%s' WHERE guid='%s' AND (storey IS NULL OR storey='Unknown');\n"
                     % (storey.replace("'", "''"), guid.replace("'", "''")))
    print("§STOREY_PATCH out=%s statements=%d" % (out_path, len(rows)))
    print("§STOREY_PATCH by_storey " + " ".join("%s=%d" % (k, v) for k, v in sorted(per_storey.items())))
    print("§STOREY_PATCH by_class  " + " ".join("%s=%d" % (k, v) for k, v in per_class.most_common(8)))
    if not rows:
        print("§STOREY_PATCH VACUOUS — nothing to patch; this DB's storeys are already complete")


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print(__doc__); sys.exit(2)
    main(sys.argv[1], sys.argv[2:])
