#!/usr/bin/env node
// Copyright (c) 2025-2026 Redhuan D. Oon <red1org@gmail.com>
// SPDX-License-Identifier: MIT
// ⚠ DO NOT REMOVE — prompts/AGENT_QUEUE.md §HYGIENE-E7. Read the log after every run.
//
// gen_equivalence_digest.js — THE RETENTION MECHANISM for E-7.
//
// THE PROBLEM (E-7, verified): the whole equivalence evidence base is gitignored. 378 logs live in
// `build/erp/*.log` and `.gitignore` excludes them, so the ledger's PASSes are re-verifiable only from
// local disk — one `git clean -x` from being prose. Un-ignoring the logs is the wrong fix: they are
// hundreds of files, some large, and they churn on every run, which is exactly why they were ignored.
//
// THE MECHANISM: commit a small TEXT DIGEST instead of the logs. For each ledger witness this records
//   · the verdict line the log actually printed (run_witness.sh's own PASS/FAIL markers — the same
//     strings the gate greps, so the digest cannot disagree with the gate),
//   · the log's sha256 + byte size + mtime.
// That is the project's own doctrine applied to evidence rather than to a DB: ship a small reviewable
// text artifact, never the binary. After a `git clean -x` the RECORD survives; re-running the bundle
// regenerates the logs and the digest must reproduce the same verdicts, and any log whose hash moved
// is visible in one `git diff`.
//
// NON-INVENT: every field is read from the log file on disk. A witness with no log is recorded as
// `(no log on disk)` — never as a pass, and never omitted.
//
// Usage: node scripts/gen_equivalence_digest.js            (writes docs/internal/ERP_EQUIVALENCE_DIGEST.md)
//        node scripts/gen_equivalence_digest.js --check    (exit 1 if any ledger VERDICT moved without the
//                                                          digest being regenerated — sha/mtime are
//                                                          provenance, not the gate; see the --check block)
'use strict';
var fs = require('fs'), path = require('path'), crypto = require('crypto');

var ROOT = path.join(__dirname, '..');
var OUT = path.join(ROOT, 'docs', 'internal', 'ERP_EQUIVALENCE_DIGEST.md');
var BUNDLE = path.join(ROOT, 'build', 'erp', 'run_bundle.sh');

// the SAME marker regexes run_witness.sh gates on — kept identical on purpose, so a verdict here can
// never disagree with the verdict the gate produced.
var PASS_RE = /🟢.*PASS|✅.*PASS|ALL PASS|OVERALL=PASS|§[A-Z0-9_-]+ PASS|[1-9][0-9]* PASS \/ 0 FAIL/;
var FAIL_RE = /🔴.*FAIL|❌.*FAIL/;
var SKIP_RE = /§HARDEN-SKIP|§BLOCKED/;

function listFrom(varName) {
  var src = fs.readFileSync(BUNDLE, 'utf8');
  var m = new RegExp('^' + varName + '="\\n([\\s\\S]*?)\\n"', 'm').exec(src);
  if (!m) return [];
  return m[1].split('\n').map(function (s) { return s.trim(); }).filter(Boolean);
}

function digestOne(script) {
  var name = path.basename(script).replace(/\.js$/, '');
  var log = path.join(ROOT, 'build', 'erp', name + '.log');
  if (!fs.existsSync(log)) return { name: name, script: script, verdict: '(no log on disk)', line: '', sha: '', size: 0, mtime: '' };
  var buf = fs.readFileSync(log);
  var text = buf.toString('utf8');
  var lines = text.split('\n').filter(function (l) { return l.trim(); });
  // the verdict line: the LAST line carrying a marker, which is what run_witness.sh's tail shows
  var vline = '';
  for (var i = lines.length - 1; i >= 0; i--) {
    if (PASS_RE.test(lines[i]) || FAIL_RE.test(lines[i]) || SKIP_RE.test(lines[i])) { vline = lines[i].trim(); break; }
  }
  var verdict = FAIL_RE.test(vline) ? 'FAIL' : SKIP_RE.test(vline) ? 'SKIP (oracle absent)' : PASS_RE.test(vline) ? 'PASS' : 'NO MARKER';
  return {
    name: name, script: script, verdict: verdict,
    line: vline.replace(/\|/g, '\\|').slice(0, 160),
    sha: crypto.createHash('sha256').update(buf).digest('hex').slice(0, 16),
    size: buf.length,
    mtime: fs.statSync(log).mtime.toISOString().slice(0, 19).replace('T', ' ')
  };
}

var tally = listFrom('TALLY_SCRIPTS'), evidence = listFrom('EVIDENCE_SCRIPTS'), oracle = listFrom('ORACLE_SCRIPTS');
if (!tally.length) { console.error('§DIGEST could not read TALLY_SCRIPTS from ' + BUNDLE); process.exit(1); }

var rows = tally.map(digestOne), evRows = evidence.map(digestOne);
var pass = rows.filter(function (r) { return r.verdict === 'PASS'; }).length;
var skip = rows.filter(function (r) { return /^SKIP/.test(r.verdict); }).length;
var fail = rows.filter(function (r) { return r.verdict === 'FAIL'; }).length;
var none = rows.filter(function (r) { return r.verdict === 'NO MARKER' || r.verdict === '(no log on disk)'; }).length;

var out = [];
out.push('# ERP Equivalence Digest — the evidence base, as a tracked text record');
out.push('');
out.push('<!-- GENERATED by scripts/gen_equivalence_digest.js — do not hand-edit. Regenerate after a bundle run. -->');
out.push('');
out.push('**Why this file exists (E-7).** The 378 witness logs under `build/erp/*.log` are gitignored, so the');
out.push('ledger\'s PASSes were re-verifiable only from local disk — one `git clean -x` from being prose. This');
out.push('digest is the retention mechanism: not the logs, but a small tracked record of **what each log said');
out.push('and what it hashed to**. After a clean, the record survives; re-running the bundle must reproduce the');
out.push('same verdicts, and any log whose content moved shows up in one `git diff`.');
out.push('');
out.push('The verdict column uses the **same marker regexes** `build/erp/run_witness.sh` gates on, so this file');
out.push('can never disagree with the gate. A witness with no log on disk is recorded as such — never as a pass,');
out.push('never omitted.');
out.push('');
out.push('**Generated:** ' + new Date().toISOString().slice(0, 19).replace('T', ' ') + ' · **tally rows:** ' + rows.length +
        ' → **' + pass + ' PASS · ' + skip + ' SKIP (oracle absent) · ' + fail + ' FAIL · ' + none + ' no verdict**');
out.push('');
out.push('The `SKIP (oracle absent)` rows are the E-8 oracle tier — they need the live iDempiere Postgres');
out.push('(`docker postgres` / `idempiere` / `idempiere_test`). They exit non-zero **on purpose**: an un-oracled');
out.push('harden witness must never read as a pass. `bash build/erp/run_bundle.sh --no-oracle` runs the other ' + (rows.length - oracle.length) + '.');
out.push('');
out.push('| # | witness | verdict | log sha256 (16) | bytes | log mtime | the line the log printed |');
out.push('|---|---|---|---|---|---|---|');
rows.forEach(function (r, i) {
  out.push('| ' + (i + 1) + ' | `' + r.name + '` | ' + r.verdict + ' | `' + r.sha + '` | ' + r.size + ' | ' + r.mtime + ' | ' + r.line + ' |');
});
if (evRows.length) {
  out.push('');
  out.push('## Evidence-only rows (do not add to the surface tally)');
  out.push('');
  out.push('| witness | verdict | log sha256 (16) | bytes | log mtime |');
  out.push('|---|---|---|---|---|');
  evRows.forEach(function (r) { out.push('| `' + r.name + '` | ' + r.verdict + ' | `' + r.sha + '` | ' + r.size + ' | ' + r.mtime + ' |'); });
}
out.push('');
var body = out.join('\n') + '\n';

if (process.argv.indexOf('--check') >= 0) {
  // WHAT --check GATES ON, and why it is not "the file is byte-identical": a log's sha256 and mtime move
  // on EVERY run (timestamps, durations, run ids are inside the logs), so a byte comparison would be red
  // on every green run — a gate that always fires is not a gate. The sha/size/mtime columns are
  // PROVENANCE, recorded at generation time so a specific historical claim can be pinned. The gate is the
  // VERDICT PER WITNESS: the set of names and what each one's log said. That is the claim the ledger
  // makes, and it is exactly what must not silently change.
  var cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  var tracked = {};
  cur.split('\n').forEach(function (l) {
    var m = /^\|\s*\d+\s*\|\s*`([a-z0-9_]+)`\s*\|\s*([^|]+?)\s*\|/.exec(l);
    if (m) tracked[m[1]] = m[2];
  });
  var moved = [], missing = [];
  rows.forEach(function (r) {
    if (!(r.name in tracked)) { missing.push(r.name); return; }
    if (tracked[r.name] !== r.verdict) moved.push(r.name + ': tracked="' + tracked[r.name] + '" now="' + r.verdict + '"');
  });
  var extra = Object.keys(tracked).filter(function (n) { return !rows.some(function (r) { return r.name === n; }); });
  var ok = moved.length === 0 && missing.length === 0 && extra.length === 0 && rows.length > 0;
  console.log('§DIGEST-CHECK rows=' + rows.length + ' tracked=' + Object.keys(tracked).length +
              ' verdictsMoved=' + moved.length + ' notInDigest=' + missing.length + ' inDigestOnly=' + extra.length +
              ' pass=' + pass + ' skip=' + skip + ' fail=' + fail + ' noverdict=' + none);
  moved.forEach(function (m) { console.log('   ↳ MOVED ' + m); });
  missing.forEach(function (m) { console.log('   ↳ NOT IN THE TRACKED DIGEST: ' + m + ' (regenerate it)'); });
  extra.forEach(function (m) { console.log('   ↳ IN THE DIGEST BUT NOT IN THE BUNDLE: ' + m + ' (a ledger row went away)'); });
  if (!rows.length) console.log('🔴 §DIGEST-CHECK INCONCLUSIVE — no ledger rows were read; nothing was judged');
  else if (ok) console.log('🟢 §DIGEST-CHECK PASS — every ledger witness\'s verdict matches the tracked digest (' + rows.length + ' rows)');
  else console.log('🔴 §DIGEST-CHECK FAIL — a ledger verdict changed without the digest being regenerated');
  process.exit(ok ? 0 : 1);
}

fs.writeFileSync(OUT, body);
console.log('§DIGEST wrote ' + path.relative(ROOT, OUT) + ' rows=' + rows.length +
            ' pass=' + pass + ' skip=' + skip + ' fail=' + fail + ' noverdict=' + none);
console.log(pass > 0 ? '🟢 §DIGEST PASS — ' + pass + ' of ' + rows.length + ' ledger witnesses have a PASS-marked log on disk, each hashed and recorded'
                     : '🔴 §DIGEST FAIL — no ledger witness has a PASS-marked log; the evidence base is empty, not retained');
