// W-LINK-SURVIVES-RENAME — whitebox §-log proof of the FUSED 4D/5D WEDGE.
// Implementing prompts/FUSED_4D5D_WEDGE_LANE.md §2 — Witness: W-LINK-SURVIVES-RENAME
//
// ISSUE PROVEN/DISPROVEN: Is our 4D schedule↔element link identity-bound (survives an element
// rename) or name-bound (breaks on rename)? Incumbents (Navisworks TimeLiner / Synchro) bind a
// schedule task to a model object by MATCHING the task NAME to the item name / selection-set /
// layer — so a rename re-resolves or BREAKS the link. We claim ours is bound on the immutable
// `output_guid` carried by the SAME signed op as the schedule window (time_machine.js:2476-2481,
// frontier by output_guid at :591) — so a rename CANNOT break it. This test runs BOTH arms on the
// SAME real element and either proves the wedge or kills it.
//
// NON-INVENT: real SampleHouse element GUIDs from elements_meta; the 4D ops are generated by the
// REAL injectGantt() sliced verbatim out of deploy/dev/time_machine.js (NOT reimplemented), with
// the REAL SEQUENCE_RULES/LABOR_RATES from deploy/dev/rates.js. Truth = the §-log read directly.
//
// Usage: node scripts/witness_link_survives_rename.js
'use strict';
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const Database = require('better-sqlite3');

const ROOT = path.join(__dirname, '..');
const TM = path.join(ROOT, 'deploy/dev/time_machine.js');
const RATES = path.join(ROOT, 'deploy/dev/rates.js');
const SRC_DB = path.join(ROOT, 'DAGCompiler/lib/input/SampleHouse_extracted.db');

let pass = 0, fail = 0;
const ok = (c, m) => { if (c) { pass++; console.log('  ✓ ' + m); } else { fail++; console.log('  ✗ FAIL ' + m); } };

// ── 1. Load the REAL sequencing rules from rates.js (run in a window-shim sandbox) ──
function loadRates() {
  const src = fs.readFileSync(RATES, 'utf8');
  const win = {};
  const sb = { window: win, console: { log() {} }, Math, JSON, Object, Array, Number, isFinite,
    parseInt, parseFloat, String, Boolean, Date, fetch: () => Promise.reject(new Error('no-fetch')) };
  sb.globalThis = sb;
  vm.createContext(sb);
  vm.runInContext(src, sb, { filename: 'rates.js' });
  return {
    SEQUENCE_RULES: sb.SEQUENCE_RULES || win.SEQUENCE_RULES || {},
    LABOR_RATES: sb.LABOR_RATES || win.LABOR_RATES || {},
    SEQUENCE_DEFAULT: sb.SEQUENCE_DEFAULT || win.SEQUENCE_DEFAULT || { phase: 'Architecture', sequence: 6, resource: null }
  };
}

// ── 2. Slice the REAL injectGantt() out of time_machine.js (verbatim, not reimplemented) ──
function loadInjectGantt(rules, getApp) {
  const src = fs.readFileSync(TM, 'utf8');
  const lines = src.split('\n');
  // injectGantt spans line 2239 ('  function injectGantt() {') to its closing '  }' before
  // 'function drawGanttMini'. Locate by markers so it survives small drifts.
  let start = -1, end = -1;
  for (let i = 0; i < lines.length; i++) {
    if (start < 0 && /^\s*function injectGantt\(\)\s*\{/.test(lines[i])) start = i;
    if (start >= 0 && /^\s*function drawGanttMini\(/.test(lines[i])) { end = i; break; }
  }
  if (start < 0 || end < 0) throw new Error('could not locate injectGantt in time_machine.js (drift?)');
  // Trim back to the function's own closing brace (last '  }' before drawGanttMini)
  let body = lines.slice(start, end);
  while (body.length && !/^\s*\}\s*$/.test(body[body.length - 1])) body.pop();
  const fnSrc = body.join('\n');
  console.log('§LINK-SLICE injectGantt lines ' + (start + 1) + '..' + (start + body.length) + ' (verbatim from time_machine.js)');

  const sb = {
    A: getApp,
    window: rules,
    console, Math, JSON, Object, Array, Number, isFinite, Infinity, Date, parseInt
  };
  sb.globalThis = sb;
  vm.createContext(sb);
  vm.runInContext(fnSrc + '\nthis.__injectGantt = injectGantt;', sb, { filename: 'injectGantt.sliced.js' });
  return sb.__injectGantt;
}

// ── sql.js-shaped wrapper over better-sqlite3 (injectGantt calls db.run / db.exec) ──
function wrapDb(better) {
  return {
    run(sql, params) { better.prepare(sql).run(...(params || [])); },
    exec(sql) {
      const stmt = better.prepare(sql);
      if (stmt.reader) {
        const cols = stmt.columns().map(c => c.name);
        const values = stmt.raw().all();
        return values.length ? [{ columns: cols, values }] : [];
      }
      stmt.run();
      return [];
    }
  };
}

// frontier rule, verbatim from time_machine.js:589-593 + :89-91 docstring:
//   placed:   start_ts <= cursor AND end_ts <= cursor
//   frontier: start_ts <= cursor < end_ts   (the element is mid-install)
// binding key = op.output_guid (time_machine.js:591). NO element_name anywhere in the bind.
function frontierAt(ops, cursor) {
  const set = new Set();
  for (const op of ops) {
    if (op.start_ts > cursor) continue;
    if (op.end_ts > cursor) set.add(op.output_guid); // mid-install = frontier
  }
  return set;
}

function readOps(better) {
  const rows = better.prepare(
    'SELECT timestamp, parameters, output_guid FROM kernel_ops WHERE undone=0 ORDER BY timestamp'
  ).raw().all();
  return rows.map(r => {
    const p = JSON.parse(r[1]);
    return { start_ts: r[0], end_ts: p._end_ts || (r[0] + 60000), output_guid: r[2], name: p.name };
  });
}

(function main() {
  console.log('\n=== W-LINK-SURVIVES-RENAME (real SampleHouse) ===');
  if (!fs.existsSync(SRC_DB)) { console.log('§LINK-ABORT missing ' + SRC_DB); process.exit(2); }

  // Work on an in-memory copy so we never mutate the canonical extracted DB.
  const better = new Database(fs.readFileSync(SRC_DB));
  const rules = loadRates();
  console.log('§LINK-RULES SEQUENCE_RULES=' + Object.keys(rules.SEQUENCE_RULES).length +
    ' LABOR_RATES=' + Object.keys(rules.LABOR_RATES).length + ' (real, from rates.js)');

  const app = { db: wrapDb(better) }; // no .scene → injectGantt sceneGuids guard skips
  const injectGantt = loadInjectGantt(rules, () => app);

  // ── BASELINE: generate ops with the REAL generator, pick a real element mid-window ──
  better.prepare('DROP TABLE IF EXISTS kernel_ops').run();
  const okGen1 = injectGantt();
  ok(okGen1 === true, 'real injectGantt generated ops');
  let ops = readOps(better);
  ok(ops.length > 0, 'kernel_ops populated (' + ops.length + ' ELEMENT_PLACE ops)');

  // Pick an element with a real non-zero install window, not at the very edges.
  ops.sort((a, b) => a.start_ts - b.start_ts);
  const mid = ops[Math.floor(ops.length / 2)];
  const G = mid.output_guid;
  const T = Math.floor((mid.start_ts + mid.end_ts) / 2); // cursor mid-install of G
  const baseFront = frontierAt(ops, T);
  console.log('§LINK-BASELINE guid=' + G + ' window=[' + mid.start_ts + ',' + mid.end_ts + '] cursorT=' + T +
    ' frontier@T=' + (baseFront.has(G) ? 1 : 0) + ' (front set size=' + baseFront.size + ')');
  ok(baseFront.has(G), 'baseline: element G is frontier at cursor T (bound by output_guid)');

  const origName = better.prepare('SELECT element_name FROM elements_meta WHERE guid=?').get(G).element_name;

  // ── CONTROL ARM (incumbent): build a NAME-keyed task map from pre-rename ops ──
  // This mimics Navisworks/Synchro: the schedule task is found for an element by its NAME.
  const nameToWindow = new Map();
  for (const op of ops) if (op.name) nameToWindow.set(op.name, { start_ts: op.start_ts, end_ts: op.end_ts });
  const preLookup = nameToWindow.get(origName);
  ok(!!preLookup, 'control: name-match resolves G by its (pre-rename) name="' + origName + '"');

  // ── RENAME: change ONLY the display label (element_name). GUID untouched. ──
  const newName = origName + ' [RENAMED-2026]';
  better.prepare('UPDATE elements_meta SET element_name=? WHERE guid=?').run(newName, G);
  const guidStill = better.prepare('SELECT guid FROM elements_meta WHERE element_name=?').get(newName).guid;
  console.log('§LINK-RENAME old="' + origName + '" new="' + newName + '" guid-unchanged=' + (guidStill === G ? G : 'CHANGED!'));
  ok(guidStill === G, 'rename changed the name but NOT the guid');

  // ── OURS after rename: regenerate via the REAL generator, recompute frontier@T ──
  better.prepare('DROP TABLE IF EXISTS kernel_ops').run();
  injectGantt();
  ops = readOps(better);
  const reFront = frontierAt(ops, T);
  const stillBound = reFront.has(G);
  const reOp = ops.find(o => o.output_guid === G);
  console.log('§LINK-OURS guid=' + G + ' frontier@T=' + (stillBound ? 1 : 0) +
    ' window=[' + (reOp ? reOp.start_ts : '?') + ',' + (reOp ? reOp.end_ts : '?') + ']' +
    ' (binding key=output_guid, name irrelevant)');
  ok(stillBound, 'OURS: rename → frontier binding at T HELD (identity by output_guid)');
  ok(reOp && reOp.start_ts === mid.start_ts && reOp.end_ts === mid.end_ts,
    'OURS: schedule window for G is byte-identical after rename (sequencing keys ifc_class, not name)');

  // ── CONTROL after rename: look up the (now renamed) element by its NEW name ──
  const postLookup = nameToWindow.get(newName); // the incumbent map was keyed on the OLD name
  const nameBroken = !postLookup;
  console.log('§LINK-NAMEMATCH lookup(new-name="' + newName + '")=' + (postLookup ? 'HIT' : 'MISS') +
    ' broken=' + (nameBroken ? 1 : 0));
  ok(nameBroken, 'CONTROL: name-match lookup MISSES after rename (reproduces incumbent breakage)');

  // ── THE VERDICT LINE ──
  console.log('§LINK-VERDICT ours=' + (stillBound ? 'HELD' : 'BROKEN') +
    ' namematch=' + (nameBroken ? 'BROKEN' : 'HELD') +
    '  → wedge ' + (stillBound && nameBroken ? 'PROVEN' : 'NOT PROVEN') + ' on real SampleHouse');

  console.log('\n  W-LINK-SURVIVES-RENAME: ' + pass + '/' + (pass + fail) + (fail ? '  ❌' : '  ✅'));
  process.exit(fail ? 1 : 0);
})();
